version = 0.1
[default.deploy.parameters]
stack_name = "dukots"
resolve_s3 = true
s3_prefix = "dukots"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
